name: Feature Request
description: Request an idea for this project.
title: ""
type: "feature"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your idea for this project.
      placeholder: Describe your issue.
    validations:
      required: true
