name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey There! Welcome to Lif Platforms. We are glad to have you here. Feel free to check out some of our other repositories while your here."
        pr-message: "Hello There! Welcome to Lif Platforms. We are glad to have you here. Feel free to check out some of our other repositories while your here."
